version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/jsforce"
    versions:
    - 1.9.26
    - 1.9.27
    - 1.9.28
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 9.2.4
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@salesforce/ts-types"
    versions:
    - 1.5.0
    - 1.5.3
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
    - 8.2.1
  - dependency-name: globby
    versions:
    - 11.0.2
  - dependency-name: tslib
    versions:
    - 2.1.0
  - dependency-name: "@oclif/plugin-help"
    versions:
    - 3.2.1
